apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-chris-superuser
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "chris-superuser"
    {{- include "cube.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "Automatically created system ChRIS admin user"
stringData:
  username: {{ .Values.chris_admin.username | quote }}
  email: {{ .Values.chris_admin.email | quote }}
data:
  {{- /*    Superuser creation process is described here: https://chrisproject.org/docs/deployment#superuser-creation */}}
  {{- /* 1. If password is supplied in values.yaml, use that. */}}
  {{- /* 2. If password was previously set, use that. */}}
  {{- /* 3. Randomly create a new password. */}}
  {{- if .Values.chris_admin.password }}
  password: {{ .Values.chris_admin.password | b64enc | quote }}
  {{- else }}
  {{- with (lookup "v1" "Secret" .Release.Namespace ( print .Release.Name "-chris-superuser"))}}
  password:  {{ index .data "password" }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- end }}
