apiVersion: apps/v1

kind: Deployment
metadata:
  name: {{ include "chris.fullname" . }}-beat
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "chris.name" . }}-beat
    app.kubernetes.io/instance: {{ .Release.Name }}-beat
    {{- include "cube.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "Celery beat"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chris.name" . }}-beat
      app.kubernetes.io/instance: {{ .Release.Name }}-beat
  template:
    metadata:
      name: {{ .Release.Name }}-beat
      namespace: {{ .Release.Namespace }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "chris.name" . }}-beat
        app.kubernetes.io/instance: {{ .Release.Name }}-beat
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: celery-beat
          image: {{ include "cube.image" . }}
          imagePullPolicy: {{ .Values.cube.image.pullPolicy }}
          command: ["celery", "-A", "core", "beat", "-l", "info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-cube-config
            - secretRef:
                name: {{ .Release.Name }}-db-config
            - secretRef:
                name: {{ .Release.Name }}-cube-secrets
          volumeMounts:
            - mountPath: /data
              name: file-storage

      volumes:
        - name: file-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-cube-files

      {{- if .Values.global.securityContext }}
      securityContext:
        {{- toYaml .Values.global.securityContext | nindent 8 }}
      {{- end }}
