---
{{- $unchangableKeys := list "DJANGO_SETTINGS_MODULE" "STORAGE_ENV" "MEDIA_ROOT" "NATS_ADDRESS" "POSTGRES_DB" "POSTGRES_USER" "POSTGRES_PASSWORD" }}
{{- $sensitiveKeys := list "DJANGO_SECRET_KEY" "AUTH_LDAP_BIND_PASSWORD" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cube-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cube.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "Configuration of ChRIS backend"
data:
  {{- with .Values.cube.config }}
    {{- if (hasKey . "CHRIS_SUPERUSER_PASSWORD" )}}
      {{- fail "Do not set .Values.cube.config.CHRIS_SUPERUSER_PASSWORD. Use .Values.chrisAdmin.password instead." }}
    {{- end }}
    {{- $config := . }}
    {{- range $sensitiveKey := $sensitiveKeys }}
      {{- if (hasKey $config $sensitiveKey) }}
        {{- fail (printf "Do not set .Values.cube.config.%s. Use .Values.cube.secrets.%s instead." $sensitiveKey $sensitiveKey) }}
      {{- end }}
    {{- end }}
    {{- range $unchangableKey := $unchangableKeys }}
      {{- if (hasKey $config $unchangableKey ) }}
        {{- fail (printf ".Values.cube.config.%s must not be set." $unchangableKey) }}
      {{- end }}
    {{- end }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  NATS_ADDRESS: {{ include "chris.nats.address" . | quote }}
  DJANGO_SETTINGS_MODULE: 'config.settings.production'
  STORAGE_ENV: 'fslink'
  MEDIA_ROOT: '/data'
  {{- if (not (hasKey (merge .Values.cube.config .Values.cube.secrets) "CHRIS_STORE_URL")) }}
  CHRIS_STORE_URL: 'https://cube.chrisproject.org/api/v1/'
  {{- end }}

---

{{- $cubeSecret := (print .Release.Name "-chris-backend") }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $cubeSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cube.labels" . | nindent 4 }}
data:
  DJANGO_SECRET_KEY: {{ include "valueOrLookupOrRandom" (dict "root" . "value" .Values.cube.secrets.DJANGO_SECRET_KEY "secret" $cubeSecret "name" "DJANGO_SECRET_KEY" "length" 32 ) }}
  CHRIS_SUPERUSER_PASSWORD: {{ include "valueOrLookupOrRandom" (dict "root" . "value" .Values.cube.secrets.CHRIS_SUPERUSER_PASSWORD "secret" $cubeSecret "name" "CHRIS_SUPERUSER_PASSWORD" "length" 16 ) }}
  {{- with .Values.cube.secrets }}
  {{- $secrets := . }}
  {{- range $unchangableKey := $unchangableKeys }}
    {{- if (hasKey $secrets $unchangableKey ) }}
      {{- fail (printf ".Values.cube.secrets.%s must not be set." $unchangableKey) }}
    {{- end }}
  {{- end }}
  {{- range $key, $secret := . }}
  {{- if (not (or (eq $key "CHRIS_SUPERUSER_PASSWORD") (eq $key "DJANGO_SECRET_KEY"))) }}
  {{ $key }}: {{ $secret | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
