apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cube.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "Configuration of a PostgresSQL database used by the ChRIS backend"
data:
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  DATABASE_HOST: "{{ .Release.Name }}-postgresql"
  DATABASE_PORT: "5432"

# TIP: password comes from the secret "{{ .Release.Name }}-postgresql" which is created by a subchart.
# https://github.com/bitnami/charts/tree/main/bitnami/postgresql
