apiVersion: apps/v1

kind: Deployment
metadata:
  name: {{ include "chris.fullname" . }}-heart
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "chris.name" . }}-heart
    {{- include "cube.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "Celery beat and private server"
spec:
  # IMPORTANT: celery beat and private server should not be replicated!
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chris.name" . }}-heart
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Release.Name }}-heart
      namespace: {{ .Release.Namespace }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "chris.name" . }}-heart
        {{- include "cube.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-db
          # N.B. hard-coded image is not necessarily same as the one used by the subchart, but should be OK
          image: docker.io/bitnami/postgresql:16.0.0-debian-11-r3
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - until pg_isready -U postgres -h {{ .Release.Name }}-postgresql -p 5432; do sleep 1; done
        - name: migratedb
          command: ["python", "manage.py", "migrate", "--noinput"]
          {{- include "cube.container" . | nindent 10 }}
        {{- if .Values.pfcon.enabled }}
        - name: create-incluster-cr
          command:
            - sh
            - -ec
            - |
              {{- /*
              - FQDN required, see https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/505
              - Name of pfcon service is brittle. I don't fully understand how subchart subtemplates are
                accessed by the parent chart. The URL is probably wrong if .Values.pfcon.nameOverride
                or .Values.pfcon.fullnameOverride is set.
              - `manager.py add` does nothing if the cr already exists
              - `manager.py modify` is called after `manager.py add` in case values are changed
              */}}
              url="http://{{ .Release.Name }}-pfcon.{{ .Release.Namespace }}.svc:{{ .Values.pfcon.service.port }}/api/v1/"
              name="{{ .Values.pfcon.name }}"
              python plugins/services/manager.py add "$name" "$url" --user "$PFCON_USER" --password "$PFCON_PASSWORD" --description {{ .Values.pfcon.description | quote }} {{ if .Values.pfcon.pfcon.config.innetwork }}--innetwork{{ end }}
              python plugins/services/manager.py modify "$name" --name "$name" --url "$url" --auth_url "${url}auth-token/" --user "$PFCON_USER" --password "$PFCON_PASSWORD" --description {{ .Values.pfcon.description | quote }} {{ if .Values.pfcon.pfcon.config.innetwork }}--innetwork{{ end }}
              plugins=({{ join " " .Values.cube.plugins }})
              for plugin_url in "${plugins[@]}"; do
                python plugins/services/manager.py register "$name" --pluginurl "$plugin_url"
              done
          {{- include "cube.container" . | nindent 10 }}
            - name: PFCON_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pfcon
                  key: PFCON_USER
            - name: PFCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pfcon
                  key: PFCON_PASSWORD
        {{- end }}
        - name: set-config
          command:
          - python
          - manage.py
          - shell
          - -c
          - |
            import os
            import json
            from core.models import ChrisInstance
            from django.contrib.auth.models import User

            chris_instance = ChrisInstance.load()
            chris_instance.job_id_prefix = {{ .Values.cube.jobPrefix | default (printf "%s-jid-" .Release.Name) | quote }}
            chris_instance.save()

            superuser_config = {
                'username': os.environ['CHRIS_SUPERUSER_USERNAME'],
                'password': os.environ['CHRIS_SUPERUSER_PASSWORD'],
                'email': os.environ['CHRIS_SUPERUSER_EMAIL']
            }
            users = [superuser_config]
            if 'PFDCM_CUBES' in os.environ:
                pfdcm_cubes = json.loads(os.environ['PFDCM_CUBES'])
                users.append({
                    'username': pfdcm_cubes['local']['username'],
                    'password': pfdcm_cubes['local']['password'],
                    'email': 'pfdcm+noreply@babymri.org'
                })

            for user_config in users:
                if (existing_user := User.objects.filter(username=user_config['username']).first()) is not None:
                    existing_user.set_password(user_config['password'])
                    existing_user.save()
                    print(f'Updated password for user "{existing_user.username}"')
                else:
                    created_user = User.objects.create_superuser(**user_config)
                    print(f'Created superuser "{created_user.username}"')
          {{- include "cube.container" . | nindent 10 }}
            - name: CHRIS_SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-chris-superuser
                  key: username
            - name: CHRIS_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-chris-superuser
                  key: password
            - name: CHRIS_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-chris-superuser
                  key: email
            {{- if .Values.pfdcm.enabled }}
            - name: PFDCM_CUBES
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pfdcm-services
                  key: cube.json
            {{- end }}

        - name: wait-rabbitmq
          command:
          - python
          - -c
          - |
            import requests
            url = 'http://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq:15672/api/aliveness-test/%2F'
            counter = 0
            status = {}
            while status != {'status': 'ok'}:
                print(f'RabbitMQ startup poll # {counter}', flush=True)
                counter += 1
                try:
                    res = requests.get(url)
                except requests.ConnectionError:
                    continue
                if res.status_code != 200:
                    continue
                status = res.json()
          {{- include "cube.container" . | nindent 10 }}

      containers:
        - name: celery-beat
          command: ["celery", "-A", "core", "beat", "-l", "info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
          {{- include "cube.container" . | nindent 10 }}
          # hard-coded resources because celery beat shouldn't require variable resources
          resources:
            requests:
              memory: 384Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 100m
        - name: server-private
          command: ["gunicorn", "-b", "0.0.0.0:8000", "-w", "1", "config.wsgi:application"]
          {{- include "cube.container" . | nindent 10 }}
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              memory: 384Mi
              cpu: 200m
            limits:
              memory: 1Gi
              cpu: 1000m
          livenessProbe:
            httpGet:
              path: /api/v1/users/
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5

      {{- include "cube.pod" . | nindent 6 }}
      {{- /* podAffinityWorkaround is needed only if using pfcon's volume */}}
      {{- if (not (include "cube.useOwnVolume" .)) }}
      {{- include "cube.podAffinityWorkaround" . | nindent 6 }}
      {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-heart
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "chris.name" . }}-heart
    {{- include "cube.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "Private ChRIS API endpoint for internal use"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "chris.name" . }}-heart
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
