{{- if .Values.cube.ingress.nodePort }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "chris.name" . }}-api-nodeport
    app.kubernetes.io/instance: {{ .Release.Name }}-api-nodeport
    {{- include "cube.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: {{ .Values.cube.ingress.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "chris.name" . }}-server
    app.kubernetes.io/instance: {{ .Release.Name }}-server
{{- end }}
