{{- if .Values.route.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "chris.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "chris.name" . }}
    {{- include "cube.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}-server
  {{- with .Values.route.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  port:
    targetPort: http
  host: {{ required ".Values.route.host is required." .Values.route.host }}
{{- end }}
