{{- $cubeSecret := include "chris.fullname" . }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $cubeSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cube.labels" . | nindent 4 }}
data:
  DJANGO_SECRET_KEY: {{ include "util.valueOrLookupOrRandom" (dict "root" . "value" .Values.cube.secrets.DJANGO_SECRET_KEY "secret" $cubeSecret "name" "DJANGO_SECRET_KEY" "length" 32) }}
  CHRIS_SUPERUSER_PASSWORD: {{ include "util.valueOrLookupOrRandom" (dict "root" . "value" .Values.cube.secrets.CHRIS_SUPERUSER_PASSWORD "secret" $cubeSecret "name" "CHRIS_SUPERUSER_PASSWORD" "length" 16) }}

  {{- with (omit .Values.cube.secrets "DJANGO_SECRET_KEY" "CHRIS_SUPERUSER_PASSWORD") }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
