{{- include "cube.deployment" (mustMerge (dict
  "name" "server"
  "command" .Values.cube.server.command
  "resources" .Values.cube.server.resources
  "replicas" .Values.cube.server.replicas
  "podAnnotations" .Values.cube.server.podAnnotations
  "httpPort" .Values.cube.server.service.port
  "hostPort" .Values.cube.server.hostPort
  "livenessProbe" (ternary (omit .Values.cube.server.livenessProbe "enabled") nil .Values.cube.server.livenessProbe.enabled)
) . ) -}}
