apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chris.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "chris.name" . }}-server
    {{- include "cube.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "ChRIS backend server"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chris.name" . }}-server
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Release.Name }}-server
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "chris.name" . }}-server
        {{- include "cube.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- include "cube.waitServerReady" . | nindent 8 }}
      containers:
        - name: server
          {{- if .Values.cube.server.command }}
          command:
          {{ .Values.cube.server.command | toYaml | nindent 10 }}
          {{- end }}
          {{- include "cube.container" . | nindent 10 }}
          ports:
            - name: http
              containerPort: 8000
          resources:
            {{- toYaml .Values.cube.server.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/v1/users/
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5

      {{- include "cube.pod" . | nindent 6 }}
      {{- include "cube.podAffinityWorkaround" . | nindent 6 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "chris.name" . }}-server
    {{- include "cube.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "chris.name" . }}-server
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
