{{- if (include "cube.useOwnVolume" .) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-cube-files
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cube.labels" . | nindent 4 }}
spec:
  {{- with .Values.cube.storage.storageClass | default .Values.global.defaultStorageClass }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
  {{- toYaml .Values.cube.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.cube.storage.size }}
{{- end }}
