apiVersion: apps/v1

kind: Deployment
metadata:
  name: {{ include "chris.fullname" . }}-worker-periodic
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "chris.name" . }}-worker-periodic
    app.kubernetes.io/instance: {{ .Release.Name }}-worker-periodic
    {{- include "cube.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "ChRIS backend periodic tasks"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chris.name" . }}-worker-periodic
      app.kubernetes.io/instance: {{ .Release.Name }}-worker-periodic
  template:
    metadata:
      name: {{ .Release.Name }}-worker-periodic
      namespace: {{ .Release.Namespace }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "chris.name" . }}-worker-periodic
        app.kubernetes.io/instance: {{ .Release.Name }}-worker-periodic
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
              # TODO WAIT FOR DATABASE READY
      containers:
        - name: worker-periodic
          command: ["celery", "-A", "core", "worker", "-c", "2", "-l", "info", "-Q", "periodic"]
          {{- include "cube.container" . | nindent 10 }}

      {{- include "cube.pod" . | nindent 6 }}

      resources:
        requests:
          memory: 128Mi
          cpu: 200m
        requests:
          memory: 128Mi
          cpu: 200m
