apiVersion: v2
name: orthanc
description: Orthanc PACS server

sources:
- https://github.com/FNNDSC/charts
- https://github.com/FNNDSC/orthanc-fnndsc
- https://hub.docker.com/r/jodogne/orthanc-plugins

type: application
version: "1.1.1"
appVersion: "1.12.3"

maintainers:
- name: The FNNDSC Dev Team
  email: dev@babyMRI.org
  url: https://fnndsc.org
