cube:
  server:
    service:
      type: NodePort
      nodePort: 32000
    command: ["gunicorn", "-b", "0.0.0.0:8000", "-w", "20", "-t", "300", "config.wsgi:application"]
    resources:
      limits:
        cpu: 12
        memory: 12Gi
      requests:
        cpu: 12
        memory: 12Gi
pfdcm:
  enabled: true
  service:
    type: NodePort
    nodePort: 32001
  listener:
    service:
      type: NodePort
      nodePort: 32004
    config:
      threads: 16
    env:
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: service.name=oxidicom
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://tempo.grafana.svc.cluster.local:4318
    resources:
      limits:
        cpu: 2
        memory: 8Gi
      requests:
        cpu: 2
        memory: 8Gi
orthanc:
  service:
    type: NodePort
    nodePort: 32003
  config:
    dicomModalities:
      "ChRIS": [ "ChRIS", "cacao-oxidicom", 11111 ]
