cube:
  # Resource requests are lowered for Github's VMs
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  workerMains:
    resources:
      requests:
        memory: 400Mi
        cpu: 100m
  workerPeriodic:
    resources:
      requests:
        memory: 400Mi
        cpu: 100m
  server:
    workers: 2
    resources:
      requests:
        memory: 512Mi
        cpu: 200m

  ingress:
    nodePort: "32000"

postgresql:
  primary:
    resources:
      requests:
        memory: 256Mi
        cpu: 200m

rabbitmq:
  resources:
    requests:
      memory: 256Mi
      cpu: 200m

pfcon:
  storage:
    size: 1Gi

  pfcon:
    resources:
      limits:
        cpu: 200m
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 384Mi

  pman:
    # It is unnecessary to increase pman's resources to above the minimum because
    # pman doesn't do anything besides sending and receiving HTTP requests.
    resources:
      limits:
        cpu: 200m
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
