cube:
  # Resource requests are lowered for Github's VMs
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  resources:
    workerMains:
      resources:
        requests:
          memory: 400Mi
          cpu: 200m
    workerPeriodic:
      resources:
        requests:
          memory: 400Mi
          cpu: 200m
    server:
      workers: 2
      resources:
        requests:
          memory: 512Mi
          cpu: 200m

  ingress:
    nodePort: "32000"

postgresql:
  primary:
    resources:
      requests:
        memory: 256Mi
        cpu: 200m

rabbitmq:
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
