cube:
  # Resource requests are lowered for Github's VMs
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  workerMains:
    resources:
      requests:
        memory: 400Mi
        cpu: 100m
  workerPeriodic:
    resources:
      requests:
        memory: 400Mi
        cpu: 100m
  server:
    workers: 2
    resources:
      requests:
        memory: 512Mi
        cpu: 200m

  ingress:
    nodePort: "32000"

postgresql:
  primary:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m

rabbitmq:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

pfcon:
  storage:
    size: 1Gi

  pfcon:
    workers: 2
    workerTimeout: 60
    resources:
      requests:
        cpu: 100m
        memory: 384Mi

  pman:
    workers: 2
    workerTimeout: 60
    resources:
      requests:
        cpu: 100m
        memory: 384Mi
