apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-pfcon
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pfcon.labels" . | nindent 4 }}
data:
  {{- with (lookup "v1" "Secret" .Release.Namespace ( print .Release.Name "-pfcon")) }}
  SECRET_KEY: {{ index .data "SECRET_KEY" }}
  PFCON_USER: {{ index .data "PFCON_USER" }}
  PFCON_PASSWORD: {{ index .data "PFCON_PASSWORD" }}
  {{- else }}
  SECRET_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  PFCON_USER: {{ "pfcon" | b64enc | quote }}
  PFCON_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
