{{- $pfconSecret := (print .Release.Name "-pfcon") -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $pfconSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pfcon.labels" . | nindent 4 }}
stringData:
  PFCON_USER: 'pfcon'
data:
  SECRET_KEY: {{ include "util.valueOrLookupOrRandom" (dict "root" . "value" .Values.pfcon.secretKey "secret" $pfconSecret "name" "SECRET_KEY" "length" 32 ) }}
  PFCON_PASSWORD: {{ include "util.valueOrLookupOrRandom" (dict "root" . "value" .Values.password "secret" $pfconSecret "name" "PFCON_PASSWORD" "length" 32 ) }}
