apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-pman
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pfcon.labels" . | nindent 4 }}
data:
  {{- with (lookup "v1" "Secret" .Release.Namespace ( print .Release.Name "-pman")) }}
  SECRET_KEY: {{ index .data "SECRET_KEY" }}
  {{- else }}
  SECRET_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
