apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pman
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pfcon.labels" . | nindent 4 }}
data:
  CONTAINER_ENV: kubernetes
  STORAGE_TYPE: kubernetes_pvc
  JOB_NAMESPACE: {{ .Release.Namespace }}
  VOLUME_NAME: {{ include "pfcon.storebase" . }}
  {{- if (hasKey .Values.pman.extraEnv "SECRET_KEY") }}
  {{- fail "Do not set pman.extraEnv.SECRET_KEY. Use pman.secretKey instead." }}
  {{- end }}
  {{- toYaml .Values.pman.extraEnv | nindent 2 }}
  {{- $setSecurityContextIsSome := kindIs "bool" .Values.pman.setSecurityContext }}
  {{- if (and (hasKey .Values.pman.extraEnv "CONTAINER_USER") $setSecurityContextIsSome (not .Values.pman.setSecurityContext)) }}
  {{- fail "Cannot set value for .Values.pman.extraEnv.CONTAINER_USER because .Values.pman.setSecurityContext=false." }}
  {{- end }}
  {{- $setSecurityContextIsNone := not $setSecurityContextIsSome }}
  {{- $isOpenShift := .Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints" }}
  {{- if (and (not (hasKey .Values.pman.extraEnv "CONTAINER_USER"))
         (or (and $setSecurityContextIsSome .Values.pman.setSecurityContext)
             (and $setSecurityContextIsNone (not $isOpenShift)))) }}
  {{- if .Values.global.podSecurityContext }}
  CONTAINER_USER: {{ printf "%d:%d" (int64 (.Values.global.podSecurityContext.runAsUser | default "1001"))
                                    (int64 (.Values.global.podSecurityContext.runAsGroup | default "0")) | quote }}
  {{- else }}
  CONTAINER_USER: "1001:0"  # default user of fnndsc/cube's base image
  {{- end }}
  {{- end }}
