
{{- /*
     * Name of this object was changed from $deprecatedName to $pfconSecret in pfcon-2.0.0,
     * so instead of calling "util.valueOrLookupOrRandom", we want to try getting the value
     * from the deprecated name as the first fallback option.
     */}}

{{- define "pfcon.valueOrLookupOrLookupDeprecatedOrRandom" }}
{{- if .value -}}
  {{- .value | b64enc | quote -}}
{{- else -}}
  {{- $namespace := .root.Release.Namespace }}
  {{- $deprecatedName := (print .root.Release.Name "-pfcon") -}}
  {{- $pfconSecret := (include "pfcon.fullname" .root) -}}
  {{- $length := .length | default 32 -}}
  {{- $name := .name -}}
  {{- if (not $name) -}}
    {{- fail (printf "pfcon.valueOrLookupOrDeprecatedOrRandom was not called with required parameter 'name'. Given parameters: %s" (keys .)) -}}
  {{- end -}}
  {{- with (lookup "v1" "Secret" $namespace $pfconSecret) -}}
    {{- if (and .data (hasKey .data $name)) -}}
      {{- (index .data $name) | quote -}}
    {{- else -}}
      {{- with (lookup "v1" "Secret" $namespace $deprecatedName) -}}
        {{- if (and .data (hasKey .data $name)) -}}
          {{- (index .data $name) | quote -}}
        {{- else }}
          {{- randAlphaNum $length | b64enc | quote -}}
        {{- end }}
      {{- else }}
        {{- randAlphaNum $length | b64enc | quote -}}
      {{- end }}
    {{- end -}}
  {{- else -}}
    {{- randAlphaNum $length | b64enc | quote -}}
  {{- end -}}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "pfcon.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pfcon.labels" . | nindent 4 }}
stringData:
  PFCON_USER: 'pfcon'
data:
  SECRET_KEY: {{ include "pfcon.valueOrLookupOrLookupDeprecatedOrRandom" (dict "root" . "value" .Values.secretKey "name" "SECRET_KEY" ) }}
  PFCON_PASSWORD: {{ include "pfcon.valueOrLookupOrLookupDeprecatedOrRandom" (dict "root" . "value" .Values.password "name" "PFCON_PASSWORD" ) }}
