{{ if not .Values.storage.existingClaim  }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-storebase
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pfcon.labels" . | nindent 4 }}
spec:
  {{- $storageClass := .Values.storage.storageClass | default .Values.global.defaultStorageClass }}
  {{- with .Values.storage.storageClass | default .Values.global.defaultStorageClass }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
  {{- toYaml .Values.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{ end }}
