{{/* Orthanc subchart */}}
{{- define "pfdcm.localOrthanc" -}}
{{- if (and .Values.pfdcm.enabled .Values.orthanc.enabled) -}}

{{/* Validate Orthanc DICOM Modalities is configured to push to pfdcmListener service */}}
{{- $aet := .Values.pfdcm.aet -}}
{{- $listenerService := include "pfdcm.listenerService" . -}}
{{- $listenerPort := .Values.pfdcm.listener.service.port -}}
{{- with (get .Values.orthanc.config.DicomModalities .Values.pfdcm.aet) -}}
{{- if (ne (index . 1 ) $listenerService) -}}
{{- fail (printf "Orthanc modality \"%s\" must have host \"%s\"" $aet $listenerService) -}}
{{- end -}}
{{- if (ne (index . 2 ) $listenerPort ) -}}
{{- fail (printf "Orthanc modality \"%s\" must have port \"%d\"" $aet (int $listenerPort)) -}}
{{- end -}}
{{- else -}}
{{- fail (
  printf ".Values.orthanc.config.DicomModalities must have an entry \"%s\": [\"%s\", \"%s\", %d]"
  $aet $aet $listenerService (int $listenerPort)
) -}}
{{- end -}}
{{ .Values.orthanc.config.dicomAet }}:
  info:
    aet: {{ .Values.pfdcm.aet | quote }}
    aet_listener: {{ .Values.pfdcm.aet | quote }}
    aec: "ORTHANC"
    serverIP: "{{ .Release.Name }}-orthanc-dicom"
    serverPort: "{{ .Values.orthanc.service.ports.dicom }}"
{{- end -}}
{{- end -}}


{{- if .Values.pfdcm.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "pfdcm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pfdcm.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "PFDCM JSON configuration files"
stringData:
  {{- /* cube.json and storage.json are both blank, because the related functionality is now handled by oxidicom. */}}
  cube.json: |
    {{ .Values.pfdcm.additionalConfig.cube | default (dict) | toJson }}
  storage.json: |
    {{ .Values.pfdcm.additionalConfig.storage | default (dict) | toJson }}
  pacs.json: |
    {{- include "pfdcm.localOrthanc" . | fromYaml | dict "services" | mustMerge .Values.pfdcm.additionalConfig.pacs | toPrettyJson | nindent 4 }}
{{- end -}}
