{{- if .Values.pfdcm.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pfdcm-listener
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pfdcm-listener
    {{- include "pfdcm.listenerLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: pfdcm-listener
  template:
    metadata:
      {{- with .Values.pfdcm.listener.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: pfdcm-listener
        {{- include "pfdcm.listenerLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chris.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      containers:
        - name: listener
          image: "{{ .Values.pfdcm.listener.image.repository }}:{{ .Values.pfdcm.listener.image.tag }}"
          imagePullPolicy: {{ .Values.pfdcm.listener.image.pullPolicy }}
          volumeMounts:
            - mountPath: /home/dicom
              name: data
          ports:
            - name: storescp
              containerPort: 11113
              protocol: TCP
          resources:
            {{- toYaml .Values.pfdcm.listener.resources | nindent 12 }}

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "pfdcm.claimName" . }}
      {{- include "pfdcm.podAffinityWorkaround" . | nindent 6 }}
{{ end }}