{{- if .Values.pfdcm.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-oxidicom
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: oxidicom
    {{- include "pfdcm.listenerLabels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "ChRIS DICOM receiver"
spec:
  replicas: {{ .Values.pfdcm.listener.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: oxidicom
  template:
    metadata:
      {{- with .Values.pfdcm.listener.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: oxidicom
        {{- include "pfdcm.listenerLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- include "cube.waitServerReady" . | nindent 8 }}
      containers:
        - name: oxidicom
          image: "{{ .Values.pfdcm.listener.image.repository }}:{{ .Values.pfdcm.listener.image.tag }}"
          imagePullPolicy: {{ .Values.pfdcm.listener.image.pullPolicy }}
          ports:
            - name: scp
              containerPort: {{ .Values.pfdcm.listener.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.pfdcm.listener.resources | nindent 12 }}
          env:
            - name: PORT
              value: {{ .Values.pfdcm.listener.service.port | quote }}
            - name: CHRIS_SCP_THREADS
              value: {{ .Values.pfdcm.listener.config.threads | quote }}
            - name: CHRIS_URL
              value: "http://{{ .Release.Name }}-server:{{ .Values.cube.server.service.port }}/api/v1/"
            - name: CHRIS_FILES_ROOT
              value: /data
              {{- if .Values.pfdcm.listener.env }}
              {{- .Values.pfdcm.listener.env | toYaml | nindent 12 }}
              {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-the-chris-user
          volumeMounts:
            - mountPath: /data
              name: file-storage

      {{- include "cube.pod" . | nindent 6 }}
      {{- include "cube.podAffinityWorkaround" . | nindent 6 }}
{{ end }}