{{- define "orthanc.dicomService" -}}
{{ .Release.Name }}-orthanc-dicom:{{ .Values.orthanc.dicomService.port }}
{{- end -}}

{{- define "oxidicom.pacsAddress" -}}
{{- if (and .Values.orthanc.enabled (not .Values.orthanc.dicomService.enabled)) -}}
{{- fail ".orthanc.dicomService.enabled must be true" -}}
{{- end -}}
{{- if .Values.pfdcm.listener.config.pacsAddress -}}
{{- if (and .Values.orthanc.enabled (not (contains (include "orthanc.dicomService" .) .Values.pfdcm.listener.config.pacsAddress))) -}}
{{- fail (printf "pfdcm.listener.config.pacsAddress must be configured with %s=\"%s\"" .Values.orthanc.config.dicomAet (include "orthanc.dicomService" .)) -}}
{{- end -}}
{{- .Values.pfdcm.listener.config.pacsAddress -}}
{{- else -}}
{{ "{" }}{{ .Values.orthanc.config.dicomAet }}={{ include "orthanc.dicomService" . | quote }}{{ "}" }}
{{- end -}}
{{- end -}}
{{- define "oxidicom.databasePoolSize" -}}
{{- if .Values.pfdcm.listener.config.databasePool -}}
{{- .Values.pfdcm.listener.config.databasePool -}}
{{- else if .Values.postgresql.primary.resources.requests.cpu -}}
{{- .Values.postgresql.primary.resources.requests.cpu -}}
{{- end -}}
{{- end -}}
{{- if .Values.pfdcm.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-oxidicom
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: oxidicom
    {{- include "pfdcm.listenerLabels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "ChRIS DICOM receiver"
spec:
  replicas: {{ .Values.pfdcm.listener.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: oxidicom
  template:
    metadata:
      {{- with .Values.pfdcm.listener.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: oxidicom
        {{- include "pfdcm.listenerLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- include "cube.waitServerReady" . | nindent 8 }}
      containers:
        - name: oxidicom
          image: "{{ .Values.pfdcm.listener.image.repository }}:{{ .Values.pfdcm.listener.image.tag }}"
          imagePullPolicy: {{ .Values.pfdcm.listener.image.pullPolicy }}
          ports:
            - name: scp
              containerPort: {{ .Values.pfdcm.listener.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.pfdcm.listener.resources | nindent 12 }}
          env:
            - name: OXIDICOM_DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  {{- if not .Values.postgresql.serviceBindings.enabled }}
                  {{- fail "Oxidicom requires the value .postgresql.serviceBindings.enabled: true" }}
                  {{- end }}
                  name: {{ .Release.Name }}-postgresql-svcbind-custom-user
                  key: uri
            - name: OXIDICOM_LISTENER_PORT
              value: {{ .Values.pfdcm.listener.service.port | quote }}
            - name: OXIDICOM_FILES_ROOT
              value: /data
            - name: OXIDICOM_SCP_AET
              value: {{ .Values.pfdcm.aet | quote }}
              {{- if (include "oxidicom.databasePoolSize" .) }}
            - name: OXIDICOM_DB_POOL
              value: {{ include "oxidicom.databasePoolSize" . | quote }}
              {{- end }}
              {{- if .Values.pfdcm.listener.config.batchSize }}
            - name: OXIDICOM_DB_BATCH_SIZE
              value: {{ .Values.pfdcm.listener.config.batchSize | quote }}
              {{- end }}
              {{- if .Values.pfdcm.listener.config.listenerThreads }}
            - name: OXIDICOM_LISTENER_THREADS
              value: {{ .Values.pfdcm.listener.config.listenerThreads | quote }}
              {{- end }}
              {{- if .Values.pfdcm.listener.config.verbose }}
            - name: OXIDICOM_VERBOSE
              value: {{ .Values.pfdcm.listener.config.verbose | quote }}
              {{- end }}
              {{- if .Values.pfdcm.listener.config.tokioThreads }}
            - name: TOKIO_WORKER_THREADS
              value: {{ .Values.pfdcm.listener.config.tokioThreads | quote }}
              {{- end }}
              {{- /* DICOM SCP Options */}}
              {{- if .Values.pfdcm.listener.config.strictPduLength }}
            - name: OXIDICOM_SCP_STRICT
              value: {{ .Values.pfdcm.listener.config.strictPduLength | quote }}
              {{- end }}
              {{- if .Values.pfdcm.listener.config.maxPduLength }}
            - name: OXIDICOM_SCP_MAX_PDU_LENGTH
              value: {{ .Values.pfdcm.listener.config.maxPduLength | quote }}
              {{- end }}
              {{- if .Values.pfdcm.listener.config.uncompressedOnly }}
            - name: OXIDICOM_SCP_UNCOMPRESSED_ONLY
              value: {{ .Values.pfdcm.listener.config.uncompressedOnly | quote }}
              {{- end }}
              {{- if .Values.pfdcm.listener.config.promiscuous }}
            - name: OXIDICOM_SCP_PROMISCUOUS
              value: {{ .Values.pfdcm.listener.config.promiscuous | quote }}
              {{- end }}
              {{- if (include "oxidicom.pacsAddress" .) }}
            - name: OXIDICOM_PACS_ADDRESS
              value: {{ include "oxidicom.pacsAddress" . | quote }}
              {{- end }}

              {{- /* Extra environment variables, manually specified */}}
              {{- if .Values.pfdcm.listener.env }}
              {{- .Values.pfdcm.listener.env | toYaml | nindent 12 }}
              {{- end }}
          volumeMounts:
            - mountPath: /data
              name: file-storage

      {{- include "cube.pod" . | nindent 6 }}
      {{- include "cube.podAffinityWorkaround" . | nindent 6 }}
{{ end }}