{{- if (and .Values.pfdcm.enabled .Values.pfdcm.service.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pfdcm
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pfdcm
    {{- include "pfdcm.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "pfdcm API. Swagger docs available on /docs"
spec:
  type: {{ .Values.pfdcm.service.type }}
  ports:
    - port: {{ .Values.pfdcm.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.pfdcm.service.nodePort }}
      nodePort: {{ .Values.pfdcm.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: pfdcm
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
