# documentation: https://helm.sh/docs/topics/charts/

apiVersion: v2
name: chris-cube
description: CUBE is an open-source platform backend for medical compute.
home: https://chrisproject.org
sources:
- https://github.com/FNNDSC/khris-helm
- https://github.com/FNNDSC/ChRIS_ultron_backEnd
keywords:
- medicine
- science
- bioinformatics
- neuroscience
- scientific workflow system

icon: ./logo_chris.png

type: application
version: "1.0.1"
appVersion: "4.0.0.pre12"

maintainers:
- name: The FNNDSC Dev Team
  email: dev@babyMRI.org
  url: https://fnndsc.org
