apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-pfdcm-services
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pfdcm.pfdcmLabels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "Configuration of the CUBE and PACS this PFDCM speaks to"
stringData:
  cube.json: |
    {{ .Values.config.cube | toPrettyJson | nindent 4 }}
  storage.json: |
    {{ .Values.config.storage | toPrettyJson | nindent 4 }}
  pacs.json: |
    {{ .Values.config.pacs | toPrettyJson | nindent 4 }}
