apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pfdcm
  labels:
    {{- include "pfdcm.pfdcmLabels" . | nindent 4 }}

spec:
  type: {{ .Values.pfdcm.service.type }}
  ports:
    - port: {{ .Values.pfdcm.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pfdcm.selectorLabels" . | nindent 4 }}
