apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pypx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pfdcm.selectorLabels" . | nindent 4 }}
    {{- include "pfdcm.commonLabels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "pypx-organized directories containing .dcm image files, DICOM metadata, and pfdcm logs."
spec:
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- else if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  accessModes:
  {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
