apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linkerd-nodeport-workaround.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "linkerd-nodeport-workaround.labels" . | nindent 4 }}
data:
  haproxy.cfg: |
    defaults
      mode http
    frontend front
      bind 0.0.0.0:{{ include "linkerd-nodeport-workaround.port" . }}
      {{- if .Values.l5dDstOverride }}
      http-request add-header l5d-dst-override {{ .Values.l5dDstOverride }}
      {{- end }}
      default_backend back
    backend back
      server server1 {{ .Values.backendServer | required "backendServer is required" }}
