apiVersion: v1
kind: Service
metadata:
  name: {{ include "linkerd-nodeport-workaround.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "linkerd-nodeport-workaround.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "linkerd-nodeport-workaround.selectorLabels" . | nindent 4 }}
