apiVersion: apps/v1

kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker-mains
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cube-worker-mains
    app.kubernetes.io/instance: {{ .Release.Name }}-worker-mains
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
  annotations:
    kubernetes.io/description: "ChRIS backend worker for main1 and main2 queues"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}-worker-mains
  template:
    metadata:
      name: {{ .Release.Name }}-worker-mains
      labels:
        app.kubernetes.io/name: cube-worker-mains
        app.kubernetes.io/instance: {{ .Release.Name }}-worker-mains
        app.kubernetes.io/part-of: {{ .Release.Name }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
      - name: worker-mains
        image: {{ .Values.image }}
        command: ["celery", "-A", "core", "worker", "-c", "4", "-l", "info", "-Q", "main1,main2"]
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-cube-config
        - secretRef:
            name: {{ .Release.Name }}-db-config
        - secretRef:
            name: {{ .Release.Name }}-cube-secrets
        volumeMounts:
          - mountPath: /var/chris
            name: file-storage
        resources:
        {{- toYaml .Values.workerMains.resources | nindent 10 }}

      volumes:
      - name: file-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-cube-files

      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
