apiVersion: v2
name: chris
description: ChRIS is an open-source platform backend for medical compute.
home: https://chrisproject.org
sources:
- https://github.com/FNNDSC/charts
- https://github.com/FNNDSC/ChRIS_ultron_backEnd
keywords:
- medicine
- science
- bioinformatics
- neuroscience
- scientific workflow system

icon: ./logo_chris.png

type: application
version: "2.0.0-alpha.1"
appVersion: "6.11.0"

maintainers:
- name: The FNNDSC Dev Team
  email: dev@babyMRI.org
  url: https://fnndsc.org

dependencies:
- name: dragonfly
  version: v1.37.0
  repository: oci://ghcr.io/dragonflydb/dragonfly/helm
  condition: dragonflydb.enabled
- name: pfcon
  version: "2.0.0"
  repository: https://fnndsc.github.io/charts
  condition: pfcon.enabled
- name: orthanc
  version: "~2.0.0"
  repository: "https://fnndsc.github.io/charts"
  condition: orthanc.enabled
- name: util
  version: "0.2.1"
  repository: "https://fnndsc.github.io/charts"
