# documentation: https://helm.sh/docs/topics/charts/

apiVersion: v2
name: chris
description: ChRIS is an open-source platform backend for medical compute.
home: https://chrisproject.org
sources:
- https://github.com/FNNDSC/charts
- https://github.com/FNNDSC/ChRIS_ultron_backEnd
keywords:
- medicine
- science
- bioinformatics
- neuroscience
- scientific workflow system

icon: ./logo_chris.png

type: application
version: "1.0.1"
appVersion: "6.3.0"

maintainers:
- name: The FNNDSC Dev Team
  email: dev@babyMRI.org
  url: https://fnndsc.org

dependencies:
- name: postgresql
  version: "~16.2.5"
  repository: "oci://registry-1.docker.io/bitnamicharts"
  condition: postgresql.enabled
- name: rabbitmq
  version: "~15.1.0"
  repository: "oci://registry-1.docker.io/bitnamicharts"
- name: nats
  version: "~8.4.10"
  repository: "oci://registry-1.docker.io/bitnamicharts"
- name: pfcon
  version: "1.0.0-alpha.2"
  repository: "https://fnndsc.github.io/charts"
  condition: pfcon.enabled
- name: orthanc
  version: "~2.0.0"
  repository: "https://fnndsc.github.io/charts"
  condition: orthanc.enabled
- name: util
  version: "0.2.1"
  repository: "https://fnndsc.github.io/charts"
