# documentation: https://helm.sh/docs/topics/charts/

apiVersion: v2
name: chris
description: ChRIS is an open-source platform backend for medical compute.
home: https://chrisproject.org
sources:
- https://github.com/FNNDSC/charts
- https://github.com/FNNDSC/ChRIS_ultron_backEnd
keywords:
- medicine
- science
- bioinformatics
- neuroscience
- scientific workflow system

icon: ./logo_chris.png

type: application
version: "0.12.0"
appVersion: "5.0.0"

maintainers:
- name: The FNNDSC Dev Team
  email: dev@babyMRI.org
  url: https://fnndsc.org

dependencies:
- name: postgresql
  version: "~13.4.4"
  repository: "oci://registry-1.docker.io/bitnamicharts"
- name: rabbitmq
  version: "~12.5.6"
  repository: "oci://registry-1.docker.io/bitnamicharts"
- name: pfcon
  version: ">=0.1.2, <0.3.0"
  repository: "https://fnndsc.github.io/charts"
  condition: pfcon.enabled
- name: orthanc
  version: "~1.2.1"
  repository: "https://fnndsc.github.io/charts"
  condition: orthanc.enabled
