# This file is for cutomizing how chris is deployed.

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

global:
  # -- StorageClass to use for PersistentVolumeClaims
  storageClass: ""

  # -- Optional security context to apply to all pods
  # podSecurityContext:
  #   runAsUser: 123456
  #   runAsGroup: 789

  # -- Bitnami subchart OpenShift compatibility settings
  # compatibility:
  #   openshift:
  #     # optional, adapt security context of Bitnami subcharts for OpenShift compatibility
  #     adaptSecurityContext: auto


# -- Ingress
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- OpenShift route
route:
  enabled: false
  host: chart-example.local
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    destinationCACertificate: ''

# -- ChRIS backend (CUBE) configuration.
cube:
  image:
    repository: ghcr.io/fnndsc/cube
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  # -- Use inter-pod affinity as a workaround for using a ReadWriteOnce PersistentVolumeClaim
  enablePodAffinityWorkaround: false

  # -- Prefix to use for job names submitted to Kubernetes. Must be a unique when the
  # -- Kubernetes namespace is used for more than one instance of CUBE.
  # -- The default behavior is to use the release name as the job prefix.
  jobPrefix:

  # -- CUBE configuration
  config:
    # -- Event polling frequency. Smaller value increases responsiveness at the cost of increased resource
    # -- usage and possible concurrency bugs.
    CUBE_CELERY_POLL_INTERVAL: "5.0"
    # -- Allowed hosts. Note: "*" is okay and convenient when OpenShift router or
    # -- k8s ingress is validating the HTTP Host header.
    DJANGO_ALLOWED_HOSTS: "*"
    DJANGO_CORS_ALLOW_ALL_ORIGINS: "true"
    DJANGO_CORS_ALLOWED_ORIGINS: ""
    DJANGO_SECURE_PROXY_SSL_HEADER: ""
    DJANGO_USE_X_FORWARDED_HOST: "false"

    # -- Enable LDAP authentication
    AUTH_LDAP: false
    # AUTH_LDAP_SERVER_URI: "ldap://192.168.0.29:389"
    # AUTH_LDAP_BIND_DN: "cn=admin,dc=fnndsc,dc=org"
    # AUTH_LDAP_USER_SEARCH_ROOT: "dc=fnndsc,dc=org"
    # AUTH_LDAP_GROUP_SEARCH_ROOT:
    # AUTH_LDAP_CHRIS_ADMIN_GROUP:

    # -- Disable user account creation via API.
    # -- If `true`, user accounts can only be created manually or
    # -- via SSO (LDAP, ...)
    # -- A value of `false` would allow anyone to create an account.
    DISABLE_USER_ACCOUNT_CREATION: true

  # -- Additional secret environment variables for CUBE.
  # -- Note: if `SECRET_KEY` is unset, its previous value will be looked up,
  # -- or a random value will be generated for you.
  secrets: {}
    # AUTH_LDAP_BIND_PASSWORD: "admin1234"
    # SECRET_KEY: supersecretkey  # https://docs.djangoproject.com/en/5.1/ref/settings/#secret-key

  # -- Set of default plugins to register with the coupled pfcon (if .pfcon.enabled)
  # -- Plugins which CUBE is hard-coded to depend on should be listed here.
  # -- To add plugins for general use, see https://chrisproject.org/docs/tutorials/upload_plugin
  plugins:
    - https://cube.chrisproject.org/api/v1/plugins/1/   # pl-dircopy
    - https://cube.chrisproject.org/api/v1/plugins/2/   # pl-tsdircopy
    - https://cube.chrisproject.org/api/v1/plugins/3/   # pl-topologicalcopy

  # -- CUBE files storage
  storage:
    # -- Enable persistent storage.
    # -- The default configuration (which is recommended for most cases)
    # -- is to share one PersistentVolumeClaim between pfcon and CUBE.
    # -- Leave `enabled=false` unless you know what you're doing.
    enabled: false
    size: 100Gi
    accessModes: [ "ReadWriteOnce" ]
    # storageClass: ""

  # -- Main celery worker configuration.
  workerMains:
    # -- Command to run for the main worker.
    command: ["celery", "-A", "core", "worker", "-c", "4", "-l", "info", "-Q", "main1,main2"]
    # -- Resources for the main worker.
    # -- If an out-of-network pfcon is configured, recommended memory limit is twice
    # -- the largest anticipated plugin instance output directory's total size.
    # -- This is because of inefficient implementation, see https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/377
    resources:
      requests:
        memory: 4Gi
        cpu: 1
      limits:
        memory: 4Gi
        cpu: 1

  # -- Periodic celery worker configuration.
  workerPeriodic:
    # -- Command to run for the periodic worker.
    command: ['celery', '-A', 'core', 'worker', '-c', '2', '-l', 'info', '-Q', 'periodic']
    # -- Resources for the periodic worker. Defaults are good enough.
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 250m

  # -- CUBE ASGI server configuration.
  server:
    # -- CUBE server pod annotations.
    podAnnotations: {}
    # -- Deployment replicas count.
    replicas: 1
    # -- Service configuration.
    service:
      type: ClusterIP
      port: 8000
      # -- CUBE server service nodePort
      nodePort:
      # -- Hostname of node from which the NodePort will be accessed.
      # -- (nodePortHost doesn't have an effect, it's only useful for NOTES.txt)
      nodePortHost:

    # -- CUBE server command.
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "config.asgi:application"]
    # -- Resources for the HTTP server (ASGI).
    resources:
      requests:
        memory: 2Gi
        cpu: 1
      limits:
        memory: 2Gi
        cpu: 1

    # -- CUBE server container hostPort.
    hostPort:

    # -- CUBE server container livenessProbe.
    livenessProbe:
      # -- Enable the livenessProbe.
      enabled: true
      httpGet:
        path: /api/v1/users/
        port: http
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 5

# -- Specify a secret containing connection parameters for the PostgreSQL database.
# -- Ignore if `postgres.enabled=true`.
postgresSecret:
  # -- Name of existing secret for the postgres connection parameters.
  # -- Required if `postgres.enabled=false`.
  name:
  keys:
    # -- Name of the key for the postgres host value.
    host: 'host'
    # -- Name of the key for the postgres port value.
    port: 'port'
    # -- Name of the key for the postgres database value.
    database: 'database'
    # -- Name of the key for the postgres username value.
    username: 'username'
    # -- Name of the key for the postgres password value.
    password: 'password'
    # -- Name of the key for the postgres uri value.
    uri: 'uri'

# -- [SUBCHART] PostgreSQL packaged by Bitnami
# -- https://github.com/bitnami/charts/tree/main/bitnami/postgresql#parameters
postgresql:
  # -- Enable the postgresql subchart. Set `enable=true` to keep life simple,
  # -- or `enable=false` if using your own existing postgres.
  enabled: true

  auth:
    database: "chris"
    username: "chris"

  # -- one of: [standalone, replication]
  architecture: standalone

  primary:
    # -- Set container resources according to one common preset (allowed values:
    # -- none, nano, micro, small, medium, large, xlarge, 2xlarge). This is ignored
    # -- if primary.resources is set (primary.resources is recommended for production).
    # -- see https://github.com/bitnami/charts/blob/973a2792e0bc5967e3180c6d44eebf223b9f1d83/bitnami/common/templates/_resources.tpl#L15-L43
    resourcesPreset: large
    # -- Set container requests and limits for different resources like CPU or memory
    # -- (essential for production workloads)
    resources: {}
    persistence:
      enabled: true
      size: 4Gi

  # Defer control of security configurations to OpenShift
  volumePermissions:
    enabled: false
  shmVolume:
    enabled: false

  # -- Create secret for service binding (Experimental)
  # -- Ref: https://servicebinding.io/service-provider/
  serviceBindings:
    enabled: true  # required

# -- [SUBCHART] RabbitMQ packaged by Bitnami
# -- https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq#parameters
rabbitmq:
  persistence:
    # -- Enable RabbitMQ data persistence using PVC
    enabled: true
    # -- PVC Storage Request for RabbitMQ data volume
    size: 1Gi

  # -- Create secret for service binding (Experimental)
  # -- Ref: https://servicebinding.io/service-provider/
  serviceBindings:
    enabled: true  # required

  # -- Set container resources according to one common preset
  # -- (allowed values: none, nano, micro, small, medium, large,
  # -- xlarge, 2xlarge). This is ignored if resources is set
  # -- (resources is recommended for production).
  resourcesPreset: small

  # -- Set container requests and limits for different resources
  # -- like CPU or memory (essential for production workloads)
  resources: {}

# -- Configuration of NATS, a messaging system. In ChRIS, NATS is used for PACS retrieve
# -- progress messages sent from oxidicom to CUBE.
# -- Documentation: https://github.com/bitnami/charts/tree/nats/8.4.3/bitnami/nats
nats:
  # -- Set container resources according to one common preset (allowed values: none,
  # -- nano, micro, small, medium, large, xlarge, 2xlarge). This is ignored if
  # -- resources is set (resources is recommended for production).
  resourcesPreset: small
  podLabels:
    app.kubernetes.io/part-of: chris
  auth:
    # -- CUBE does not support NATS authorization
    enabled: false

# -- Configuration of pfcon, the ChRIS compute controller
pfcon:
  enabled: true

  name: "innetwork"
  description: "Kubernetes cluster compute resource"
  replicaCount: 1
  podAnnotations: {}
  podSecurityContext: {}

  service:
    type: ClusterIP
    port: 5005

  nodeSelector: {}

  # -- Storage space for CUBE files should be configured here.
  # -- It is recommended to allocate as much space as possible for CUBE files.
  storage:
    existingClaim: ""
    size: 100Gi
    accessModes: [ "ReadWriteOnce" ]
    # storageClass:

  pfcon:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 384Mi

    # -- pfcon configuration
    # -- Recommended to keep as-is
    config:
      innetwork: true
      storageEnv: fslink

    # -- Extra environment variables.
    extraEnv:
      GUNICORN_CMD_ARGS: "--workers=4 --timeout=3600"

  pman:
    # It is unnecessary to increase pman's resources to above the minimum because
    # pman doesn't do anything besides sending and receiving HTTP requests.
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi

    workers: 4
    workerTimeout: 30

    # -- pman configuration
    # -- https://github.com/FNNDSC/pman#environment-variables
    # -- N.B.: SECRET_KEY, CONTAINER_ENV, STORAGE_TYPE, VOLUME_NAME, and CONTAINER_USER
    # -- are handled automatically, and should not be manually set.
    config:
      JOB_LABELS: chrisproject.org/job=plugininstance
      ENABLE_HOME_WORKAROUND: "yes"
      REMOVE_JOBS: "yes"
      IGNORE_LIMITS: "no"

    # -- Set securityContext of containers created by pman to have the same securityContext as .global.podSecurityContext
    # -- or the default fnndsc/cube container user, so that the container user can write to the shared volume's filesystem.
    # -- Default behavior is to detect whether on OpenShift: if so, set as false, true otherwise.
    setSecurityContext: true


# -- Configuration of PFDCM, the ChRIS PACS interface
pfdcm:
  enabled: false
  image:
    repository: ghcr.io/fnndsc/pfdcm
    pullPolicy: IfNotPresent
    tag: "3.1.22"
  podAnnotations: {}
  service:
    enabled: true
    type: ClusterIP
    port: 4005
    # nodePort:
  # -- OpenShift route configuration
  route:
    enabled: false
    host: chart-example.local
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
      destinationCACertificate: ''
  replicas: 1
  maxWorkers: 8
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 4Gi

  # DICOM application entity title
  aet: "ChRIS"

  # Additional pfdcm configuration. Usually, you'll want to leave this empty.
  # pfdcm will be preconfigured with the CUBE and Orthanc of this chart.
  # If this pfdcm interacts with multiple CUBEs or multiple PACS servers,
  # add them here.
  additionalConfig:
    cube: {}
      # local:
      #   url: https://cube.example.org/api/v1/
      #   username: pfdcm
      #   password: pfdcm1234
    storage: {}
      # local:
      #   storagetype: fs
      #   storepath: /files
    pacs:
      services: {}
        # orthanc:
        #   info:
        #     aet: CHRISLOCAL
        #     aet_listener: ORTHANC
        #     aec: ORTHANC
        #     serverIP: orthanc
        #     serverPort: 4242

  # DICOM listener for pfdcm. Enabled when pfdcm is enabled.
  listener:
    image:
      repository: ghcr.io/fnndsc/oxidicom
      pullPolicy: Always
      tag: "pr-3"
    podAnnotations: {}
    # -- (optional) hostPort for DICOM listener
    hostPort:
    # -- The PACS server must be configured to push to this service.
    # -- If using Orthanc, the Helm chart will help you validate your
    # -- configuration of Orthanc's modailities to include this service.
    service:
      enabled: true
      type: ClusterIP
      port: 11111
      # nodePort: 30033
    replicas: 1
    ## manual configuration of OpenTelemetry
    # env:
    #   - name: OTEL_RESOURCE_ATTRIBUTES
    #     value: service.name=oxidicom
    #   - name: OTEL_EXPORTER_OTLP_ENDPOINT
    #     value: http://tempo:4317

    # -- Optional configurations of oxidicom.
    config:
      # -- number of DICOM listener threads
      # -- ref: https://chrisproject.org/docs/oxidicom/deployment#performance-tuning
      listenerThreads: 8

      # -- number of Tokio runtime threads
      # -- ref: https://chrisproject.org/docs/oxidicom/deployment#performance-tuning
      tokioThreads: 4

      # -- enable/disable logging and set verbosity of components
      logging: oxidicom=warn

      ## strictPduLength, uncompressedOnly, and maxPduLength are strange DICOM
      ## options which you probably want to leave as their default values.
      # strictPduLength: true
      # uncompressedOnly: true
      # maxPduLength: 16384
      ## Whether to accept unknown DICOM transfer syntaxes.
      # promiscuous: true

    resources:
      # It's written in Rust!
      # Memory usage typically stays under 20MiB, unless there is backpressure
      # from slow disk write speed
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi

# -- Orthanc open-source PACS server
orthanc:
  # -- Enable Orthanc. If true, it is recommended to also set pfdcm.enabled=true.
  enabled: false
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  # -- (optional) set hostPort for Orthanc's HTTP API
  hostPort:
  # -- (optional) set hostPort for Orthanc's PACS DIMSE port
  dicomHostPort:

  # -- Orthanc HTTP API and web app
  service:
    enabled: true
    type: ClusterIP
    port: 8042
    # nodePort:
  # -- PACS server
  dicomService:
    enabled: true
    type: ClusterIP
    port: 4242
    # nodePort:
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 1
      memory: 4Gi
  config:
    # The logical name of this instance of Orthanc. This one is
    # displayed in Orthanc Explorer and at the URI "/system".
    name: "Orthanc"
    # Enable the transparent compression of the DICOM instances
    storageCompression: false
    # Action to take when the maximum storage is reached.
    # By default, the patients are recycled ("Recycle" mode).
    # In "Reject" mode, the sender will receive a 0xA700 DIMSE status code
    # if the instance was sent through C-Store, a 507 HTTP status code
    # if using the REST API and a 0xA700 Failure reason when using
    # DicomWeb Stow-RS 
    # Allowed values: "Recycle", "Reject"
    # (new in Orthanc 1.11.2)
    maximumStorageMode: Reject
    # Maximum size of the storage cache in MB.  The storage cache
    # is stored in RAM and contains a copy of recently accessed
    # files (written or read).  A value of "0" indicates the cache
    # is disabled.  (new in Orthanc 1.10.0)
    maximumStorageCacheSize: 0

    # The DICOM Application Entity Title
    dicomAet: "ORTHANC"
    # Check whether the called AET corresponds during a DICOM request
    dicomCheckCalledAet: false

    # The default encoding that is assumed for DICOM files without
    # "SpecificCharacterSet" DICOM tag, and that is used when answering
    # C-Find requests (including worklists). The allowed values are
    # "Ascii", "Utf8", "Latin1", "Latin2", "Latin3", "Latin4",
    # "Latin5", "Cyrillic", "Windows1251", "Arabic", "Greek", "Hebrew",
    # "Thai", "Japanese", and "Chinese".
    defaultEncoding: "Latin1"

    # Set the timeout (in seconds) after which the DICOM associations
    # are closed by the Orthanc SCP (server) if no further DIMSE
    # command is received from the SCU (client).
    dicomScpTimeout: 30

    # The timeout (in seconds) after which the DICOM associations are
    # considered as closed by the Orthanc SCU (client) if the remote
    # DICOM SCP (server) does not answer.
    dicomScuTimeout: 10

    # Whether or not the password protection is enabled
    authenticationEnabled: true

    # The list of the registered users. Because Orthanc uses HTTP
    # Basic Authentication, the passwords are stored as plain text.
    registeredUsers: {}

    # The list of the known DICOM modalities
    #
    # A fourth parameter is available to enable patches for a
    # specific PACS manufacturer. The allowed values are currently
    # "Generic" (default value), "StoreScp" (storescp tool from
    # DCMTK), "ClearCanvas", "MedInria", "Dcm4Chee", "SyngoVia",
    # "AgfaImpax" (Agfa IMPAX), "EFilm2" (eFilm version 2), and
    # "Vitrea". This parameter is case-sensitive.
    dicomModalities:
      # !!!IMPORTANT!!!
      # To use in combination with pfdcm, you MUST define a modality for
      # `.Values.pfdcm.aet`
      "ChRIS": [ "ChRIS", "NAME-oxidicom", 11111 ]
      # "clearcanvas" : [ "CLEARCANVAS", "192.168.1.1", 104, "ClearCanvas" ]

    # Whether Orthanc monitors its metrics (new in Orthanc 1.5.4). If
    # set to "true", the metrics can be retrieved at
    # "/tools/metrics-prometheus" formetted using the Prometheus
    # text-based exposition format.
    metricsEnabled: false

  ohif:
    enabled: true
    # BTW, it's impossible to configure Orthanc's OHIF to connect with pfdcm-dicomweb.

    # OHIF custom config file
    # https://orthanc.uclouvain.be/book/plugins/ohif.html#user-configuration-of-ohif
    # userConfiguration: |
    #   window.config = {
    #     extensions: [],
    #     modes: []
    #   }

  persistence:
    storage:
      size: 1Gi
      # storageClass: my-storage-class
      accessModes: [ ReadWriteOnce ]
    index:
      size: 1Gi
      # storageClass: my-storage-class
      accessModes: [ ReadWriteOnce ]
