apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rabbitmq
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}-rabbitmq
    app.kubernetes.io/version: "3"
    app.kubernetes.io/component: queue
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
  annotations:
    kubernetes.io/description: "ChRIS backend asynchronous task queue"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}-rabbitmq
  template:
    metadata:
      name: {{ .Release.Name }}-rabbitmq
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/instance: {{ .Release.Name }}-rabbitmq
        app.kubernetes.io/version: "3"
        app.kubernetes.io/component: queue
        app.kubernetes.io/part-of: {{ .Release.Name }}
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
      - name: rabbitmq
        image: docker.io/library/rabbitmq:3
        ports:
        - name: amqp
          containerPort: 5672

      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: rabbitmq-service
    app.kubernetes.io/instance: {{ .Release.Name }}-rabbitmq-service
    app.kubernetes.io/version: "3"
    app.kubernetes.io/component: queue
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}-rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
