{{- if .Values.dicomService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orthanc.fullname" . }}-dicom
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "orthanc.name" . }}-dicom
    {{- include "orthanc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dicomService.type }}
  ports:
    - port: {{ .Values.dicomService.port }}
      targetPort: dicom
      protocol: TCP
      name: dicom
      {{- if .Values.dicomService.nodePort }}
      nodePort: {{ .Values.dicomService.nodePort }}
      {{- end }}

  selector:
    {{- include "orthanc.selectorLabels" . | nindent 4 }}
{{- end }}
