apiVersion: v1
kind: Service
metadata:
  name: {{ include "orthanc.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "orthanc.name" . }}-headless
    {{- include "orthanc.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  clusterIP: None
  selector:
    {{- include "orthanc.selectorLabels" . | nindent 4 }}
