{{- if .Values.objectStorage.enabled }}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ include "orthanc.bucket-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orthanc.labels" . | nindent 6 }}
  {{- with .Values.objectStorage.annotations }}
  annotations:
    {{- include . | nindent 6 }}
  {{- end }}
spec:
  generateBucketName: {{ include "orthanc.fullname" . }}
  storageClassName: {{ .Values.objectStorage.storageClass }}
  {{- with .Values.objectStorage.additionalConfig }}
  additionalConfig:
    {{- include . | nindent 4 }}
  {{- end }}
{{- end }}
