{{- if .Values.crunchyPgo.enabled }}
{{- if .Values.persistence.index.enabled }}
  {{- fail "Cannot enable both crunchyPgo and persistence.index" }}
{{- end }}
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ include "orthanc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orthanc.labels" . | nindent 4 }}
  {{- with (merge .Values.crunchyPgo.annotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml .Values.crunchyPgo.spec | nindent 2 }}
{{- end }}
