{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "orthanc.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.metrics.prometheusRule.namespace }}
  labels:
    {{- merge .Values.metrics.prometheusRule.labels (dict "app.kubernetes.io/component" "metrics") (include "orthanc.labels" . | fromYaml) | toYaml | nindent 4 }}
  {{- with (merge .Values.metrics.prometheusRule.annotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  groups:
    - name: {{ include "orthanc.fullname" . }}
      rules:
        {{- toYaml .Values.metrics.prometheusRule.rules | nindent 8 }}
{{- end }}
