{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orthanc.fullname" . }}
  labels:
    {{- include "orthanc.labels" . | nindent 4 }}
  {{- with (merge .Values.service.annotations .Values.commonAnnotations )}}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.config.HttpServerEnabled }}
    - port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.config.HttpPort }}
      protocol: TCP
      name: http
      {{- with (dig "nodePorts" "http" nil .Values.service) }}
      nodePort: {{ . }}
      {{- end }}
    {{- end }}
    {{- if .Values.config.DicomServerEnabled }}
    - port: {{ .Values.service.ports.dicom }}
      targetPort: {{ .Values.config.DicomPort }}
      protocol: TCP
      name: dicom
      {{- with (dig "nodePorts" "dicom" nil .Values.service) }}
      nodePort: {{ . }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "orthanc.selectorLabels" . | nindent 4 }}
{{- end }}
