apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "orthanc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orthanc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "orthanc.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "orthanc.fullname" . }}-headless
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orthanc.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "orthanc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: dicom
              containerPort: {{ .Values.dicomService.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: storage
              mountPath: /var/lib/orthanc/storage
            - name: index
              mountPath: /var/lib/orthanc/index
            - name: config
              readOnly: true
              mountPath: /etc/orthanc
      
      volumes:
        - name: config
          secret:
            secretName: {{ include "orthanc.fullname" . }}
            optional: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes:
      {{- toYaml .Values.persistence.storage.accessModes | nindent 8 }}
      {{- if .Values.persistence.storage.storageClass }}
      storageClassName: {{ .Values.persistence.storage.storageClass }}
      {{- else if .Values.global.storageClass }}
      storageClassName: {{ .Values.global.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.storage.size }}
  - metadata:
      name: index
    spec:
      accessModes:
      {{- toYaml .Values.persistence.index.accessModes | nindent 8 }}
      {{- if .Values.persistence.index.storageClass }}
      storageClassName: {{ .Values.persistence.index.storageClass }}
      {{- else if .Values.global.storageClass }}
      storageClassName: {{ .Values.global.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.index.size }}
