apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "orthanc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orthanc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "orthanc.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "orthanc.fullname" . }}-headless
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orthanc.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "orthanc.serviceAccountName" . }}
      {{- with (merge .Values.podSecurityContext .Values.global.podSecurityContext) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
              {{- if .Values.hostPort }}
              hostPort: {{ .Values.hostPort }}
              {{- end }}
            - name: dicom
              containerPort: {{ .Values.dicomService.port }}
              protocol: TCP
              {{- if .Values.dicomHostPort }}
              hostPort: {{ .Values.dicomHostPort }}
              {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: storage
              mountPath: /var/lib/orthanc/storage
            - name: index
              mountPath: /var/lib/orthanc/index
            - name: config
              readOnly: true
              mountPath: /etc/orthanc
      volumes:
        - name: config
          secret:
            secretName: {{ include "orthanc.fullname" . }}
            optional: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      {{- with .Values.persistence.storage.accessModes }}
      accessModes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.persistence.storage.storageClass | default .Values.global.storageClass) }}
      storageClassName: {{ . }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.storage.size }}
  - metadata:
      name: index
    spec:
      {{- with .Values.persistence.index.accessModes }}
      accessModes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.persistence.index.storageClass | default .Values.global.storageClass) }}
      storageClassName: {{ . }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.index.size }}

