name: ci

on:
  push:
    branches: [ master ]

jobs:
  test-cube:
    name: Test CUBE
    runs-on: ubuntu-22.04

    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Start Kubernetes
      run: kind create cluster --config=testing/kind-with-nodeport.yml
    - name: Update Helm dependencies
      run: helm dependency update ./charts/chris
    - name: Install chris
      run: |
        helm install --create-namespace --namespace ghactions khris-test \
          -f testing/ghactions-values.yml --set nodePortHost=$(hostname) ./charts/chris

    - name: Wait for migrations to complete
      run: ./testing/wait_for_migration.sh -n ghactions

    - name: Connectivity test
      run: helm test -n ghactions khris-test
    # - name: User test
      # run: ...

    - name: Uninstall chart
      run: helm uninstall -n ghactions khris-test
    - name: Delete cluster
      run: kind delete cluster
  
  # https://helm.sh/docs/howto/chart_releaser_action/
  release:
    needs: [ test-cube ]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
