name: Release Chart

on:
  push:
    branches: [ master ]
    paths:
      - 'charts/**'
      - '.github/workflows/release.yml'

jobs:
  # https://helm.sh/docs/howto/chart_releaser_action/
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Update Helm repos
        run: |
          helm repo add fnndsc https://fnndsc.github.io/charts
          helm repo add oauth2-proxy https://oauth2-proxy.github.io/manifests
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
