name: Unit Tests

on:
  push:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Discover tests
        id: find
        run: |
          test_dirs="$(find -mindepth 3 -maxdepth 3 -type d -name tests -print0)"
          if [ -z "$test_dirs" ]; then
            echo "::error ::No test directories found."
            exit 1
          fi
          chart_dirs="$(echo "$test_dirs" | xargs -0 dirname | tr '\n' '\0')"
          echo "chart_dirs=$chart_dirs" >> "$GITHUB_OUTPUT"
      - name: Update Helm dependencies
        run: |
          echo '${{ steps.find.outputs.chart_dirs }}' \
            | xargs -0 -L 1 helm dependency update
      - name: Install helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git --version v0.6.3
      - name: Run unit tests
        run: |
          echo '${{ steps.find.outputs.chart_dirs }}' \
            | xargs -0 -L 1 helm unittest

