name: Test Orthanc

on:
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/test-orthanc.yml'
      - 'charts/orthanc/**'

jobs:
  test:
    name: Test Orthanc
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create kind cluster
        run: kind create cluster
      - name: Install Orthanc
        run: helm install orthanc ./charts/orthanc
      - name: Wait for Orthanc to be ready
        run: kubectl rollout status statefulset orthanc
      - name: Test
        run: helm test orthanc
      - name: Uninstall
        run: helm uninstall orthanc
      - name: Delete kind cluster
        run: kind delete cluster
